apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/dohyun-99/edu_baseinfo:v1 #ghcr.io/dohyun-99/elastic_backend:v1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prd"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: github-secret
